apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seatrain-base.fullname" . }}-secrets
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-10"
type: Opaque
stringData:
{{- if .Values.global.commonSecrets -}}
  {{- range $key, $value := .Values.global.commonSecrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}


