apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-1"
data:
  REDIS_URL: redis://{{ .Release.Name }}-redis-master.default.svc.cluster.local
{{- if .Values.global.commonEnv -}}
  {{- range $key, $value := .Values.global.commonEnv }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
