apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seatrain-base.fullname" . }}-rails
  labels:
    {{- include "seatrain-base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.rails.replicaCount }}
  selector:
    matchLabels:
      {{- include "seatrain-base.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "seatrain-base.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
    {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.global.rails.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "seatrain-base.fullname" . }}
          securityContext:
            {{- toYaml .Values.global.rails.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - bundle 
            - exec
            - rails
          args:
            - "server"
            - "-b"
            - "0.0.0.0"
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: {{ include "seatrain-base.fullname" . }}-secrets
          {{- with .Values.global.rails.livenessProbe }}
          livenessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.rails.readinessProbe }}
          readinessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.global.rails.resources | nindent 14 }}
      {{- with .Values.global.rails.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.global.rails.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.rails.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
