apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seatrain-base.fullname" . }}-sidekiq
  labels:
{{ include "seatrain-base.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.global.sidekiq.replicaCount }}
  selector:
    matchLabels:
      {{- include "seatrain-base.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: background
  template:
    metadata:
      labels:
        {{- include "seatrain-base.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: background
    spec:
    {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.global.sidekiq.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "seatrain-base.fullname" . }}
          securityContext:
            {{- toYaml .Values.global.sidekiq.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: sidekiqalive
              containerPort: 7433
          command:
            - bundle
            - exec
            - sidekiq
          args:
            - "-C"
            - "config/sidekiq.yml"
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: {{ include "seatrain-base.fullname" . }}-secrets
          {{- with .Values.global.sidekiq.livenessProbe }}
          livenessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.sidekiq.readinessProbe }}
          readinessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.global.sidekiq.resources | nindent 14 }}
      {{- with .Values.global.sidekiq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.global.sidekiq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.sidekiq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
